# Generated by Django 4.1.7 on 2023-04-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.UUIDField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('valor', models.FloatField(max_length=50)),
                ('lancamento', models.DateField()),
            ],
        ),
    ]
