# Generated by Django 4.1.7 on 2023-04-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria_pedro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='id_livro',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
