# Generated by Django 4.1.7 on 2023-04-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria_pedro', '0002_alter_livros_id_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='id_livro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
