# Generated by Django 4.1.7 on 2023-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria_pedro', '0003_alter_livros_id_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
